# Generated by Django 5.0.2 on 2024-02-23 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('civil', 'Civil'), ('militar', 'Militar')], max_length=10)),
                ('nome', models.TextField(max_length=255)),
                ('rg', models.FloatField()),
                ('motivo', models.TextField(max_length=255)),
                ('data', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
